version: "3"
services:
  ingress-asb:
    image: "iot-for-tillgenglighet/ingress-azure-servicebus:latest"
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: "no"
    environment:
      DIWISE_ASB_CONNECTIONSTRING: $INGRESS_ASB_CONNSTR
      DIWISE_ASB_TOPICPATH: "tillgangligavagar"
      DIWISE_ASB_SUBSCRIPTIONNAME: "tillgangligavagarSub"
      DIWISE_CONTEXT_BROKER_URL: "http://localhost"
      DIWISE_MAX_SEGMENT_DISTANCE: "30"

    ports:
      - "5000:5000"
